/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: neon_dust (https://sketchfab.com/h_miller)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-fallen-tree-85be5e12759d460cb5f1f0d7a4c109b6
title: Cartoon fallen tree
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_5: THREE.Mesh;
		Object_9: THREE.Mesh;
		Object_11: THREE.Mesh;
		Object_13: THREE.Mesh;
		Object_15: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_19: THREE.Mesh;
		Object_21: THREE.Mesh;
		Object_23: THREE.Mesh;
		Object_27: THREE.Mesh;
		Object_29: THREE.Mesh;
		Object_31: THREE.Mesh;
		Object_33: THREE.Mesh;
		Object_35: THREE.Mesh;
		Object_37: THREE.Mesh;
		Object_39: THREE.Mesh;
		Object_41: THREE.Mesh;
		Object_43: THREE.Mesh;
		Object_45: THREE.Mesh;
		Object_47: THREE.Mesh;
		Object_49: THREE.Mesh;
		Object_51: THREE.Mesh;
		Object_53: THREE.Mesh;
		Object_55: THREE.Mesh;
		Object_57: THREE.Mesh;
		Object_59: THREE.Mesh;
		Object_61: THREE.Mesh;
		Object_63: THREE.Mesh;
		Object_65: THREE.Mesh;
		Object_67: THREE.Mesh;
		Object_69: THREE.Mesh;
		Object_71: THREE.Mesh;
		Object_73: THREE.Mesh;
		Object_25: THREE.Mesh;
		Object_77: THREE.Mesh;
		Object_79: THREE.Mesh;
		Object_81: THREE.Mesh;
		Object_83: THREE.Mesh;
		Object_85: THREE.Mesh;
		Object_87: THREE.Mesh;
		Object_89: THREE.Mesh;
		Object_91: THREE.Mesh;
		Object_93: THREE.Mesh;
		Object_95: THREE.Mesh;
		Object_97: THREE.Mesh;
		Object_99: THREE.Mesh;
		Object_75: THREE.Mesh;
		Object_7: THREE.Mesh;
	};
	materials: {
		floor: THREE.MeshStandardMaterial;
		grass_001: THREE.MeshStandardMaterial;
		["grass_001.001"]: THREE.MeshStandardMaterial;
		["grass_001.002"]: THREE.MeshStandardMaterial;
		["grass_001.003"]: THREE.MeshStandardMaterial;
		["grass_001.004"]: THREE.MeshStandardMaterial;
		["grass_001.005"]: THREE.MeshStandardMaterial;
		["log_inside.001"]: THREE.MeshStandardMaterial;
		log_inside: THREE.MeshStandardMaterial;
		["Material.001"]: THREE.MeshStandardMaterial;
		["Material.011"]: THREE.MeshStandardMaterial;
		["Material.006"]: THREE.MeshStandardMaterial;
		["Material.002"]: THREE.MeshStandardMaterial;
		["Material.003"]: THREE.MeshStandardMaterial;
		["Material.004"]: THREE.MeshStandardMaterial;
		["Material.010"]: THREE.MeshStandardMaterial;
		["Material.012"]: THREE.MeshStandardMaterial;
		["Material.008"]: THREE.MeshStandardMaterial;
		["Material.009"]: THREE.MeshStandardMaterial;
		["Material.007"]: THREE.MeshStandardMaterial;
		["Material.005"]: THREE.MeshStandardMaterial;
		mushroom_stem: THREE.MeshStandardMaterial;
		["mushroom_stem.008"]: THREE.MeshStandardMaterial;
		["mushroom_stem.009"]: THREE.MeshStandardMaterial;
		["mushroom_stem.002"]: THREE.MeshStandardMaterial;
		["mushroom_stem.003"]: THREE.MeshStandardMaterial;
		["mushroom_stem.001"]: THREE.MeshStandardMaterial;
		["mushroom_stem.004"]: THREE.MeshStandardMaterial;
		["mushroom_stem.005"]: THREE.MeshStandardMaterial;
		["mushroom_stem.011"]: THREE.MeshStandardMaterial;
		["mushroom_stem.006"]: THREE.MeshStandardMaterial;
		["mushroom_stem.010"]: THREE.MeshStandardMaterial;
		["mushroom_stem.007"]: THREE.MeshStandardMaterial;
		log_moss: THREE.MeshStandardMaterial;
		["grass_001.006"]: THREE.MeshStandardMaterial;
		["grass_001.007"]: THREE.MeshStandardMaterial;
		["grass_001.016"]: THREE.MeshStandardMaterial;
		["grass_001.017"]: THREE.MeshStandardMaterial;
		["grass_001.008"]: THREE.MeshStandardMaterial;
		["grass_001.009"]: THREE.MeshStandardMaterial;
		["grass_001.010"]: THREE.MeshStandardMaterial;
		["grass_001.011"]: THREE.MeshStandardMaterial;
		["grass_001.012"]: THREE.MeshStandardMaterial;
		["grass_001.013"]: THREE.MeshStandardMaterial;
		["grass_001.014"]: THREE.MeshStandardMaterial;
		["grass_001.015"]: THREE.MeshStandardMaterial;
		["log_moss.001"]: THREE.MeshStandardMaterial;
		log_main: THREE.MeshStandardMaterial;
	};
};

export function FallenTree(props: JSX.IntrinsicElements["group"]) {
	//@ts-ignore
	const { nodes, materials } = useGLTF("/fallenTree.glb") as GLTFResult;
	return (
		<group {...props} dispose={null} scale={0.16} receiveShadow>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group rotation={[Math.PI / 2, 0, 0]}>
						<group
							position={[293.41, -162.6, -0.24]}
							rotation={[-Math.PI / 2, 0, 0]}
							scale={100}
						>
							{/* <mesh
								geometry={nodes.Object_5.geometry}
								material={materials.floor}
							/> */}
						</group>
						<group
							position={[321.65, -174.44, -8.69]}
							rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
							scale={100}
						>
							<group
								position={[0.1, 0.56, 0.47]}
								rotation={[-2.88, Math.PI / 2, 0]}
								scale={0.69}
							>
								<mesh
									geometry={nodes.Object_9.geometry}
									material={materials.grass_001}
								/>
							</group>
							<group
								position={[0.1, 0.7, 0.28]}
								rotation={[-2.35, Math.PI / 2, 0]}
								scale={0.74}
							>
								<mesh
									geometry={nodes.Object_11.geometry}
									material={materials["grass_001.001"]}
								/>
							</group>
							<group
								position={[0.14, -0.61, 0.31]}
								rotation={[2.96, Math.PI / 2, 0]}
								scale={0.7}
							>
								<mesh
									geometry={nodes.Object_13.geometry}
									material={materials["grass_001.002"]}
								/>
							</group>
							<group
								position={[0.14, -0.19, 0.52]}
								rotation={[-2.22, Math.PI / 2, 0]}
								scale={0.75}
							>
								<mesh
									geometry={nodes.Object_15.geometry}
									material={materials["grass_001.003"]}
								/>
							</group>
							<group
								position={[0.1, 1.44, -0.28]}
								rotation={[3.13, Math.PI / 2, 0]}
								scale={0.79}
							>
								<mesh
									geometry={nodes.Object_17.geometry}
									material={materials["grass_001.004"]}
								/>
							</group>
							<group
								position={[0.1, 1.41, -0.49]}
								rotation={[-2.22, Math.PI / 2, 0]}
								scale={0.73}
							>
								<mesh
									geometry={nodes.Object_19.geometry}
									material={materials["grass_001.005"]}
								/>
							</group>
							<group position={[-0.28, 1.22, 0.02]}>
								<mesh
									geometry={nodes.Object_21.geometry}
									material={materials["log_inside.001"]}
								/>
							</group>
							<group position={[-0.28, -1.54, 0]} rotation={[Math.PI, 0, 0]}>
								<mesh
									geometry={nodes.Object_23.geometry}
									material={materials.log_inside}
								/>
							</group>
							<group
								position={[-0.59, 0.06, -0.09]}
								rotation={[0, -0.13, Math.PI / 2]}
							>
								<group
									position={[-0.8, -0.2, 0.41]}
									rotation={[1.81, -0.02, 0.98]}
									scale={0.94}
								>
									<mesh
										geometry={nodes.Object_27.geometry}
										material={materials["Material.001"]}
									/>
								</group>
								<group
									position={[0.04, -0.29, 0.46]}
									rotation={[1.66, -0.1, -0.83]}
									scale={0.87}
								>
									<mesh
										geometry={nodes.Object_29.geometry}
										material={materials["Material.011"]}
									/>
								</group>
								<group
									position={[-0.11, -0.25, 0.37]}
									rotation={[1.78, -0.07, 0.43]}
									scale={0.78}
								>
									<mesh
										geometry={nodes.Object_31.geometry}
										material={materials["Material.006"]}
									/>
								</group>
								<group
									position={[-0.72, -0.09, 0.25]}
									rotation={[1.74, 0.1, 2.35]}
									scale={0.72}
								>
									<mesh
										geometry={nodes.Object_33.geometry}
										material={materials["Material.002"]}
									/>
								</group>
								<group
									position={[0.62, -0.07, 0.46]}
									rotation={[1.6, -0.02, -1.8]}
									scale={1.02}
								>
									<mesh
										geometry={nodes.Object_35.geometry}
										material={materials["Material.003"]}
									/>
								</group>
								<group
									position={[0.77, -0.11, 0.37]}
									rotation={[1.79, -0.05, 0.68]}
									scale={0.75}
								>
									<mesh
										geometry={nodes.Object_37.geometry}
										material={materials["Material.004"]}
									/>
								</group>
								<group
									position={[-0.68, -0.15, 0.34]}
									rotation={[1.79, 0.06, 1.71]}
									scale={0.67}
								>
									<mesh
										geometry={nodes.Object_39.geometry}
										material={materials["Material.010"]}
									/>
								</group>
								<group
									position={[-0.96, -0.09, 0.39]}
									rotation={[1.77, 0.08, 1.99]}
									scale={0.59}
								>
									<mesh
										geometry={nodes.Object_41.geometry}
										material={materials["Material.012"]}
									/>
								</group>
								<group
									position={[-0.31, -0.27, 0.38]}
									rotation={[1.81, 0, 1.15]}
									scale={0.95}
								>
									<mesh
										geometry={nodes.Object_43.geometry}
										material={materials["Material.008"]}
									/>
								</group>
								<group
									position={[-0.35, -0.34, 0.57]}
									rotation={[1.8, 0.19, 1.59]}
									scale={0.95}
								>
									<mesh
										geometry={nodes.Object_45.geometry}
										material={materials["Material.009"]}
									/>
								</group>
								<group
									position={[-0.21, -0.29, 0.53]}
									rotation={[1.65, 0.1, -3.07]}
									scale={0.98}
								>
									<mesh
										geometry={nodes.Object_47.geometry}
										material={materials["Material.007"]}
									/>
								</group>
								<group
									position={[-0.09, -0.36, 0.54]}
									rotation={[1.6, 0.01, -2.05]}
									scale={0.46}
								>
									<mesh
										geometry={nodes.Object_49.geometry}
										material={materials["Material.005"]}
									/>
								</group>
								<group
									position={[-0.79, -0.31, 0.39]}
									rotation={[0.13, -0.99, 0]}
									scale={0.94}
								>
									<mesh
										geometry={nodes.Object_51.geometry}
										material={materials.mushroom_stem}
									/>
								</group>
								<group
									position={[0.04, -0.4, 0.44]}
									rotation={[0.13, 0.83, 0]}
									scale={0.87}
								>
									<mesh
										geometry={nodes.Object_53.geometry}
										material={materials["mushroom_stem.008"]}
									/>
								</group>
								<group
									position={[-0.1, -0.35, 0.35]}
									rotation={[0.13, -0.43, 0]}
									scale={0.78}
								>
									<mesh
										geometry={nodes.Object_55.geometry}
										material={materials["mushroom_stem.009"]}
									/>
								</group>
								<group
									position={[-0.71, -0.16, 0.25]}
									rotation={[2.97, -0.78, -Math.PI]}
									scale={0.72}
								>
									<mesh
										geometry={nodes.Object_57.geometry}
										material={materials["mushroom_stem.002"]}
									/>
								</group>
								<group
									position={[0.61, -0.19, 0.44]}
									rotation={[-3.01, 1.35, Math.PI]}
									scale={1.02}
								>
									<mesh
										geometry={nodes.Object_59.geometry}
										material={materials["mushroom_stem.003"]}
									/>
								</group>
								<group
									position={[-0.68, -0.21, 0.33]}
									rotation={[-3.01, -1.43, -Math.PI]}
									scale={0.67}
								>
									<mesh
										geometry={nodes.Object_61.geometry}
										material={materials["mushroom_stem.001"]}
									/>
								</group>
								<group
									position={[0.75, -0.2, 0.39]}
									rotation={[-0.4, -0.68, 0]}
									scale={0.75}
								>
									<mesh
										geometry={nodes.Object_63.geometry}
										material={materials["mushroom_stem.004"]}
									/>
								</group>
								<group
									position={[-0.96, -0.16, 0.38]}
									rotation={[-3.01, -1.14, -Math.PI]}
									scale={0.59}
								>
									<mesh
										geometry={nodes.Object_65.geometry}
										material={materials["mushroom_stem.005"]}
									/>
								</group>
								<group
									position={[-0.3, -0.38, 0.37]}
									rotation={[0.13, -1.15, 0]}
									scale={0.95}
								>
									<mesh
										geometry={nodes.Object_67.geometry}
										material={materials["mushroom_stem.011"]}
									/>
								</group>
								<group
									position={[-0.32, -0.42, 0.56]}
									rotation={[1.79, -1.15, 1.65]}
									scale={0.84}
								>
									<mesh
										geometry={nodes.Object_69.geometry}
										material={materials["mushroom_stem.006"]}
									/>
								</group>
								<group
									position={[-0.21, -0.4, 0.53]}
									rotation={[-3.01, 0.07, -Math.PI]}
									scale={0.98}
								>
									<mesh
										geometry={nodes.Object_71.geometry}
										material={materials["mushroom_stem.010"]}
									/>
								</group>
								<group
									position={[-0.1, -0.42, 0.53]}
									rotation={[-3.01, 1.09, Math.PI]}
									scale={0.46}
								>
									<mesh
										geometry={nodes.Object_73.geometry}
										material={materials["mushroom_stem.007"]}
									/>
								</group>
								<mesh
									geometry={nodes.Object_25.geometry}
									material={materials.log_moss}
								/>
							</group>
							<group
								position={[-0.59, 0.06, -0.09]}
								rotation={[0, -0.13, Math.PI / 2]}
							>
								<group
									position={[0.23, -0.03, -0.07]}
									rotation={[0.26, -0.29, 2.52]}
									scale={0.69}
								>
									<mesh
										geometry={nodes.Object_77.geometry}
										material={materials["grass_001.006"]}
									/>
								</group>
								<group
									position={[0.17, 0.03, -0.05]}
									rotation={[1.28, -0.04, 2.34]}
									scale={0.59}
								>
									<mesh
										geometry={nodes.Object_79.geometry}
										material={materials["grass_001.007"]}
									/>
								</group>
								<group
									position={[0.28, 0, 0.04]}
									rotation={[1.82, -0.43, 2.74]}
									scale={0.63}
								>
									<mesh
										geometry={nodes.Object_81.geometry}
										material={materials["grass_001.016"]}
									/>
								</group>
								<group
									position={[-0.16, -0.11, -0.08]}
									rotation={[0, 0.21, 0.62]}
									scale={0.59}
								>
									<mesh
										geometry={nodes.Object_83.geometry}
										material={materials["grass_001.017"]}
									/>
								</group>
								<group
									position={[-0.23, 0.01, 0.04]}
									rotation={[-3.08, 0.9, 0.71]}
									scale={0.61}
								>
									<mesh
										geometry={nodes.Object_85.geometry}
										material={materials["grass_001.008"]}
									/>
								</group>
								<group
									position={[-0.12, 0.03, -0.06]}
									rotation={[1.45, 0.21, 1.76]}
									scale={0.68}
								>
									<mesh
										geometry={nodes.Object_87.geometry}
										material={materials["grass_001.009"]}
									/>
								</group>
								<group
									position={[0.11, 0.04, 0]}
									rotation={[1.78, -0.1, 1.08]}
									scale={0.69}
								>
									<mesh
										geometry={nodes.Object_89.geometry}
										material={materials["grass_001.010"]}
									/>
								</group>
								<group
									position={[-0.12, 0.03, 0.02]}
									rotation={[1.49, 0.01, -1.09]}
									scale={0.61}
								>
									<mesh
										geometry={nodes.Object_91.geometry}
										material={materials["grass_001.011"]}
									/>
								</group>
								<group
									position={[0.13, 0.04, 0.01]}
									rotation={[1.78, -0.1, 1.48]}
									scale={0.62}
								>
									<mesh
										geometry={nodes.Object_93.geometry}
										material={materials["grass_001.012"]}
									/>
								</group>
								<group
									position={[-0.03, -0.01, 0.15]}
									rotation={[2.02, 0.14, -2.48]}
									scale={0.65}
								>
									<mesh
										geometry={nodes.Object_95.geometry}
										material={materials["grass_001.013"]}
									/>
								</group>
								<group
									position={[-0.09, 0.06, 0.1]}
									rotation={[2.53, 0.26, 0.98]}
									scale={0.6}
								>
									<mesh
										geometry={nodes.Object_97.geometry}
										material={materials["grass_001.014"]}
									/>
								</group>
								<group
									position={[0.2, 0.04, -0.05]}
									rotation={[1.57, -0.61, 0.14]}
									scale={0.62}
								>
									<mesh
										geometry={nodes.Object_99.geometry}
										material={materials["grass_001.015"]}
									/>
								</group>
								<mesh
									geometry={nodes.Object_75.geometry}
									material={materials["log_moss.001"]}
								/>
							</group>
							<mesh
								geometry={nodes.Object_7.geometry}
								material={materials.log_main}
							/>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/fallenTree.glb");
