/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ralez (https://sketchfab.com/ralez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-ground-with-grass-and-stones-8752ea5fa49b48ac99778b70b1ee1434
title: Stylized ground with grass and stones
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['branch_Duplicator|branch_-_copy|Dupli|_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|1_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|2_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|3_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|4_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|5_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|6_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|7_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|8_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|9_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|10_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|11_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|12_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|13_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|14_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|15_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|16_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|17_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|18_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|19_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|20_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|21_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|22_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|23_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|24_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|25_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|26_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|27_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|28_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|29_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|30_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|31_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|32_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|33_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|34_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|35_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|36_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|37_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|38_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|39_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|40_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|41_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|42_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|43_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|44_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|45_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|46_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|47_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|48_BRANCH_0']: THREE.Mesh
    ['branch_Duplicator|branch_-_copy|Dupli|49_BRANCH_0']: THREE.Mesh
    ['branch_-_copy_BRANCH_0']: THREE.Mesh
    branch_Duplicator__0: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|1_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|2_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|3_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|4_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|5_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|6_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|7_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|8_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|9_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|10_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|11_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|12_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|13_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|14_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|15_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|16_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|17_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|18_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|19_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|20_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|21_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|22_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|23_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|24_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|25_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|26_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|27_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|28_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|29_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|30_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|31_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|32_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|33_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|34_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|35_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|36_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|37_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|38_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|39_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|40_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|41_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|42_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|43_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|44_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|45_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|46_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|47_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|48_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|49_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|50_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|51_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|52_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|53_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|54_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|55_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|56_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|57_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|58_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|59_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|60_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|61_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|62_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|63_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|64_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|65_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|66_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|67_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|68_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|69_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|70_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|71_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|72_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|73_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|74_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|75_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|76_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|77_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|78_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|79_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|80_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|81_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|82_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|83_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|84_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|85_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|86_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|87_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|88_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|89_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|90_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|91_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|92_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|93_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|94_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|95_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|96_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|97_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|98_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|99_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|100_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|101_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|102_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|103_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|104_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|105_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|106_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|107_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|108_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|109_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|110_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|111_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|112_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|113_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|114_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|115_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|116_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|117_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|118_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|119_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|120_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|121_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|122_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|123_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|124_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|125_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|126_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|127_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|128_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|129_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|130_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|131_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|132_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|133_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|134_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|135_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|136_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|137_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|138_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|139_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|140_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|141_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|142_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|143_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|144_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|145_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|146_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|147_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|148_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|149_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|150_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|151_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|152_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|153_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|154_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|155_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|156_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|157_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|158_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|159_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|160_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|161_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|162_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|163_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|164_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|165_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|166_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|167_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|168_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|169_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|170_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|171_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|172_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|173_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|174_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|175_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|176_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|177_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|178_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|179_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|180_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|181_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|182_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|183_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|184_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|185_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|186_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|187_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|188_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|189_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|190_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|191_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|192_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|193_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|194_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|195_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|196_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|197_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|198_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|199_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|200_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|201_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|202_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|203_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|204_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|205_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|206_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|207_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|208_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|209_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|210_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|211_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|212_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|213_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|214_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|215_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|216_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|217_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|218_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|219_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|220_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|221_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|222_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|223_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|224_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|225_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|226_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|227_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|228_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|229_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|230_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|231_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|232_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|233_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|234_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|235_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|236_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|237_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|238_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|239_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|240_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|241_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|242_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|243_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|244_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|245_ROCK_0']: THREE.Mesh
    ['rock_Duplicator|rock_-_copy|Dupli|246_ROCK_0']: THREE.Mesh
    ['rock_-_copy_ROCK_0']: THREE.Mesh
    rock_Duplicator__0: THREE.Mesh
    GROUND001_GROUND001_0: THREE.Mesh
    grass099_GRASS_0: THREE.Mesh
    grass099_GRASS_0_1: THREE.Mesh
    grass099_GRASS_0_2: THREE.Mesh
    grass099_GRASS_0_3: THREE.Mesh
    grass099_GRASS_0_4: THREE.Mesh
  }
  materials: {
    BRANCH: THREE.MeshStandardMaterial
    branch_Duplicator__0: THREE.MeshStandardMaterial
    ROCK: THREE.MeshStandardMaterial
    ['GROUND.001']: THREE.MeshStandardMaterial
    GRASS: THREE.MeshStandardMaterial
  }
}

export function StylizedGround(props: JSX.IntrinsicElements['group']) {
  //@ts-ignore
  const { nodes, materials } = useGLTF('/stylizedGround.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.05}>
      <group position={[-82.16, -6.88, 69.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-1.45, 0.5, 0.07]} rotation={[-1.83, -0.85, -1.15]} scale={0.06}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.34, 3.22, 0.23]} rotation={[1.71, 0.94, -3.13]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|1_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-1.36, -4, 0.08]} rotation={[-2.32, 0.09, 1.21]} scale={0.06}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|2_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-3.08, 2.34, 0.21]} rotation={[-1.91, -0.11, 0.28]} scale={0.18}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|3_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.02, 4.15, 0.05]} rotation={[-1.78, 0.24, -0.56]} scale={0.04}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|4_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.27, 3.82, 0.12]} rotation={[-2.56, -1.11, -2.71]} scale={0.1}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|5_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[1.9, -1.87, 0.25]} rotation={[-2.69, 1.27, 2.26]} scale={0.22}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|6_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[3.56, 3.21, 0.03]} rotation={[2.86, 0.39, -2.94]} scale={0.02}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|7_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.17, 4.82, 0.3]} rotation={[-1.89, -0.96, -0.35]} scale={0.26}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|8_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[5.81, -1.43, 0.22]} rotation={[-2.21, -1.19, 2.52]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|9_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.46, 0.9, 0.16]} rotation={[-2.01, -1.39, 2.16]} scale={0.13}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|10_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.32, -0.53, 0.08]} rotation={[-2.05, 0.91, -1.17]} scale={0.07}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|11_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.98, -1.89, 0.25]} rotation={[1.74, 0.36, -3.01]} scale={0.22}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|12_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[1.19, -3.13, 0.19]} rotation={[2.01, -0.27, 1.8]} scale={0.17}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|13_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[3.28, -1.93, 0.22]} rotation={[3.02, 1.37, -3.14]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|14_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.68, -1.59, 0.08]} rotation={[1.62, 0.27, 2.21]} scale={0.07}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|15_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.55, 3.89, 0.02]} rotation={[2.79, -0.57, 3.1]} scale={0.02}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|16_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[3.83, 2.77, 0.22]} rotation={[-3.07, 0.43, 1.58]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|17_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[1.76, 1.7, 0.19]} rotation={[1.67, 0.22, -2.46]} scale={0.16}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|18_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-3.2, -3.18, 0.05]} rotation={[-2.11, -0.5, -2.08]} scale={0.04}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|19_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.8, -3.26, 0]} rotation={[3.01, -0.07, 2.85]} scale={0}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|20_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[4.59, -0.49, 0.07]} rotation={[-1.6, 0.76, 2.87]} scale={0.06}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|21_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-0.71, -4.04, 0.11]} rotation={[2.27, 0.97, -0.06]} scale={0.09}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|22_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-3.67, 2.01, 0.3]} rotation={[-2.28, 0.38, -2.05]} scale={0.26}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|23_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.34, -2.99, 0.3]} rotation={[2.04, -0.32, -1.57]} scale={0.26}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|24_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[3.5, 3.48, 0.19]} rotation={[2.1, -0.84, -0.79]} scale={0.16}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|25_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.26, 4.18, 0.27]} rotation={[-1.81, -0.9, 1.14]} scale={0.23}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|26_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[1.79, 1.65, 0.22]} rotation={[-1.68, -0.77, -0.34]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|27_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[3.47, -0.35, 0.2]} rotation={[-2.98, -0.07, 1.61]} scale={0.17}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|28_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.63, -3.3, 0.12]} rotation={[-3.09, -0.61, 3.13]} scale={0.1}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|29_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-3.97, -3.12, 0.07]} rotation={[-2.07, -0.27, 0.23]} scale={0.06}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|30_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-4.85, -0.4, 0.29]} rotation={[1.75, 0.28, -0.33]} scale={0.25}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|31_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.56, -2.79, 0.06]} rotation={[-2.87, 0.91, 0.5]} scale={0.05}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|32_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[4.66, 0.71, 0.08]} rotation={[-2.66, 0.42, -0.12]} scale={0.07}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|33_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.16, -4.14, 0.24]} rotation={[-2.04, -0.95, -1.83]} scale={0.2}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|34_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-1.9, -0.32, 0.08]} rotation={[-1.88, -0.95, 0.9]} scale={0.07}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|35_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-2.11, 1.45, 0.1]} rotation={[-1.76, 0.53, -3.11]} scale={0.09}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|36_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-0.83, -1.02, 0.19]} rotation={[-2.48, -0.03, -1.92]} scale={0.17}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|37_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-0.72, -3.64, 0.22]} rotation={[2.97, -0.2, -0.65]} scale={0.19}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|38_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[4.84, 2.17, 0.27]} rotation={[2.79, 1.43, 1.13]} scale={0.23}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|39_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.48, 1.44, 0.17]} rotation={[-1.77, 0.69, 0.01]} scale={0.14}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|40_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[4.38, -2.88, 0.15]} rotation={[2.14, -0.47, -2.57]} scale={0.13}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|41_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-1.06, -4, 0.25]} rotation={[1.58, 0.59, -3.01]} scale={0.22}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|42_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.59, -3.62, 0.28]} rotation={[2.22, -0.18, -2.03]} scale={0.24}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|43_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.92, 1.47, 0.16]} rotation={[-2.4, 0.86, 0.84]} scale={0.14}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|44_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-0.8, 4.77, 0.17]} rotation={[2.8, -0.43, -2.63]} scale={0.15}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|45_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[4.2, -2.7, 0]} rotation={[-1.94, 0.59, -2.22]} scale={0}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|46_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[-0.92, 4.79, 0.02]} rotation={[2.3, 0.4, 0.42]} scale={0.02}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|47_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[2.75, -4.02, 0]} rotation={[-3.07, -0.8, 0.36]} scale={0}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|48_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group position={[0.73, 4.74, 0.24]} rotation={[-1.6, -0.15, 1.97]} scale={0.21}>
              <mesh geometry={nodes['branch_Duplicator|branch_-_copy|Dupli|49_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <group scale={0.86}>
              <mesh geometry={nodes['branch_-_copy_BRANCH_0'].geometry} material={materials.BRANCH} />
            </group>
            <mesh geometry={nodes.branch_Duplicator__0.geometry} material={materials.branch_Duplicator__0} />
          </group>
          <group position={[0, -45.63, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[5.51, 1.22, 0.29]} rotation={[-0.6, 0.36, 1.97]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.13, 2.32, 0.47]} rotation={[0.44, -0.74, 1.11]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|1_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.74, 1.41, 0.28]} rotation={[1.12, 0, -0.16]} scale={[-0.06, 0.06, 0.06]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|2_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.53, -0.31, 0.67]} rotation={[0.54, 0.51, -1.64]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|3_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.82, 2.64, 0.62]} rotation={[-1.05, -0.78, 2.84]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|4_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.33, -5.26, 0.27]} rotation={[1.26, 0.6, 1.32]} scale={[-0.06, 0.06, 0.06]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|5_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.7, 1.1, 0.58]} rotation={[-1.12, -0.79, -3.01]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|6_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.97, -5.59, 0.51]} rotation={[-0.42, -0.09, -1.07]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|7_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.35, -6.06, 0.36]} rotation={[-1.76, -1.25, 2.75]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|8_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.72, -2.14, 0.42]} rotation={[-1.37, -0.45, -1.71]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|9_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.81, -5.85, 0.35]} rotation={[0.17, -0.95, -2.08]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|10_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.07, 1.9, 0.18]} rotation={[-0.37, 0.44, -0.9]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|11_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.29, 1.4, 0.28]} rotation={[0.89, -0.37, -1.2]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|12_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.98, -0.97, 0.5]} rotation={[1.2, -0.94, -0.89]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|13_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.43, -4.84, 0.34]} rotation={[-0.97, -0.75, 1.61]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|14_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.24, 1.65, 0.61]} rotation={[1.53, 0.13, 0.76]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|15_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.82, -4.47, 0.52]} rotation={[0.15, 0.4, 2.43]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|16_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.23, -1.39, 0.2]} rotation={[0.11, -0.15, -2.36]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|17_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.87, 4.08, 0.48]} rotation={[-0.91, 0.43, -0.03]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|18_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.66, -1.07, 0.5]} rotation={[1.03, 0.55, 2.46]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|19_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.93, -2.22, 0.61]} rotation={[-0.51, 0.85, -0.97]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|20_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.35, 5.48, 0.22]} rotation={[0.44, -1.04, 1.1]} scale={[-0.04, 0.04, 0.04]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|21_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.74, -0.59, 0.33]} rotation={[1.11, -0.88, -0.26]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|22_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.22, -0.29, 0.4]} rotation={[-1.76, -1.01, -2.62]} scale={[-0.12, 0.12, 0.12]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|23_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.92, -3.09, 0.51]} rotation={[-1.72, -1.16, -2.12]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|24_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.55, 2.2, 0.18]} rotation={[1.95, -1.07, 2.1]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|25_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.49, -4.03, 0.31]} rotation={[0.56, -1.17, -0.34]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|26_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1, 4.31, 0.46]} rotation={[-1.2, -0.88, 2.33]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|27_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.48, 0.95, 0.67]} rotation={[-1.75, -0.9, -1.57]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|28_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.47, 0.07, 0.58]} rotation={[-1.23, 0.83, -0.29]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|29_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.61, 1.84, 0.38]} rotation={[-1.59, -0.58, 0.64]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|30_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.16, 4.45, 0.47]} rotation={[-0.05, 0.98, -2.58]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|31_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.14, 1.72, 0.15]} rotation={[0.77, 0.41, 1.9]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|32_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.86, 2.47, 0.17]} rotation={[0.32, 0.15, 2.06]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|33_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.14, 2.72, 0.15]} rotation={[-0.08, -0.1, -3.07]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|34_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.7, 5.13, 0.5]} rotation={[1.42, 0.09, -0.96]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|35_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.46, 1.03, 0.6]} rotation={[-1.62, -0.46, 2.64]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|36_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.65, 1.72, 0.42]} rotation={[-1.21, -0.67, -2.82]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|37_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.93, -0.4, 0.31]} rotation={[0.83, -1.42, -2.26]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|38_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.99, 1.92, 0.67]} rotation={[1.22, -1.03, 1.38]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|39_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.1, -3.8, 0.24]} rotation={[1.27, -0.11, 2.08]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|40_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.05, 5.55, 0.49]} rotation={[1.19, 0.62, -0.01]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|41_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.98, -1.82, 0.6]} rotation={[-0.13, 0.57, 1.03]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|42_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.9, -4.19, 0.2]} rotation={[1.08, 0.91, -2.58]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|43_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.11, 3.41, 0.43]} rotation={[1.13, -0.19, 2.34]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|44_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.52, -2.13, 0.5]} rotation={[-0.98, 0.35, -2.08]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|45_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.52, 3.98, 0.26]} rotation={[0.98, -0.06, -0.19]} scale={[-0.06, 0.06, 0.06]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|46_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.01, 5.56, 0.2]} rotation={[-0.56, -0.27, -2.65]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|47_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.92, 2.05, 0.61]} rotation={[1.23, -0.16, 1.35]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|48_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.04, -5.03, 0.55]} rotation={[-1.51, -1.35, 1.67]} scale={[-0.2, 0.2, 0.2]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|49_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.06, 4.29, 0.27]} rotation={[-1.04, 0.42, -2.25]} scale={[-0.06, 0.06, 0.06]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|50_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.4, 2.41, 0.36]} rotation={[1.7, -0.52, 2.96]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|51_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.79, -2.05, 0.63]} rotation={[1.65, -0.93, 2.96]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|52_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.33, -5.4, 0.35]} rotation={[0.75, -0.75, -1.15]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|53_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.37, 4.51, 0.19]} rotation={[-0.01, 1.24, 0.86]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|54_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.66, -0.79, 0.58]} rotation={[0.07, 0.3, -1.91]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|55_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.7, 1.52, 0.63]} rotation={[-1.02, -0.95, 1.22]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|56_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.3, -4.11, 0.32]} rotation={[0.92, 0.17, -2.86]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|57_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.01, 0.95, 0.32]} rotation={[1.03, 0.06, -0.4]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|58_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.24, -1.61, 0.46]} rotation={[-0.75, -0.53, 0.06]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|59_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.96, 4.74, 0.26]} rotation={[1.71, -0.54, -0.75]} scale={[-0.06, 0.06, 0.06]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|60_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.52, 3.94, 0.55]} rotation={[-1.2, 0.54, -2.96]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|61_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.55, -1.54, 0.4]} rotation={[-1.36, -1.16, 1.36]} scale={[-0.12, 0.12, 0.12]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|62_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.5, -4.82, 0.49]} rotation={[0.49, -0.37, -0.01]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|63_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.64, -0.59, 0.64]} rotation={[1.16, -1.21, 0.65]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|64_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.37, -5.69, 0.32]} rotation={[-1.16, 0.14, 1.67]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|65_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.43, -0.1, 0.56]} rotation={[0.64, 0.6, -2.48]} scale={[-0.2, 0.2, 0.2]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|66_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.29, 3.78, 0.38]} rotation={[-0.81, -0.87, 2.31]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|67_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.51, -3.59, 0.46]} rotation={[1.79, -0.74, 0.27]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|68_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.42, -2.96, 0.17]} rotation={[-1.03, 1.07, -0.75]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|69_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.74, -5.21, 0.45]} rotation={[1.47, -1.35, -1.37]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|70_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.12, 0.8, 0.62]} rotation={[-0.76, 0.74, 3.08]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|71_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.26, 1.04, 0.55]} rotation={[-0.09, 0.03, 0.43]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|72_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.55, 1.19, 0.29]} rotation={[-0.62, -0.47, 2.77]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|73_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.71, 4.44, 0.15]} rotation={[-1.46, -0.02, 2.73]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|74_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.39, 3.4, 0.25]} rotation={[1.33, -0.15, 2.88]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|75_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.6, -0.33, 0.48]} rotation={[-1.02, 0.07, -1.46]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|76_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.42, -4.4, 0.36]} rotation={[-0.21, 1.14, 0.52]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|77_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.88, -1.65, 0.48]} rotation={[-1.24, -0.26, 2.31]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|78_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.3, -2.06, 0.28]} rotation={[-1.8, -1.12, 2.96]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|79_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.85, -2.25, 0.18]} rotation={[-0.34, 0.78, 0.22]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|80_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.26, 4.7, 0.56]} rotation={[0.24, 0.15, 2.07]} scale={[-0.2, 0.2, 0.2]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|81_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.2, 5.85, 0.51]} rotation={[1.55, -0.56, -2.77]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|82_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.07, 5.86, 0.33]} rotation={[1.4, 0.3, 0.66]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|83_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.92, 3.5, 0.52]} rotation={[0.81, -0.49, 2.14]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|84_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2, 0.29, 0.55]} rotation={[0.94, 0.91, -2.45]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|85_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.51, 2.38, 0.69]} rotation={[1.27, 0.1, -0.27]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|86_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.14, 0.92, 0.25]} rotation={[-3.09, -1.46, 1.55]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|87_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.29, 3.54, 0.16]} rotation={[1.37, 0.33, 0.37]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|88_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.44, 3.38, 0.64]} rotation={[-0.41, 0.74, -0.02]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|89_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.27, 3.61, 0.24]} rotation={[-0.65, -0.42, -1.03]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|90_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.82, -0.52, 0.52]} rotation={[0.15, 0.4, 2.43]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|91_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.72, 2.59, 0.45]} rotation={[0.35, -1.52, -1.68]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|92_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.17, -5.08, 0.61]} rotation={[-1.41, -0.19, 2.78]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|93_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.19, -3.17, 0.41]} rotation={[1.25, -0.28, 2.38]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|94_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.06, -0.8, 0.49]} rotation={[-0.45, -0.08, 0.79]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|95_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.21, 0.82, 0.31]} rotation={[0.83, -1.42, -2.26]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|96_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.66, -2.44, 0.47]} rotation={[-1.25, -0.38, 0]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|97_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.21, -2.76, 0.31]} rotation={[0.83, -1.42, -2.26]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|98_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.93, 4.96, 0.6]} rotation={[0.13, 1.09, 0.71]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|99_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.81, -5.03, 0.59]} rotation={[0.73, 0.73, -0.76]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|100_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.99, 1.51, 0.69]} rotation={[-0.94, 0.39, 1.29]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|101_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.49, -4.66, 0.5]} rotation={[0.72, -0.25, 1.88]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|102_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[6.12, 1.65, 0.54]} rotation={[1.3, -0.76, -0.52]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|103_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.06, -3.08, 0.45]} rotation={[1.62, -0.91, 0.24]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|104_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.65, 2.35, 0.23]} rotation={[1.07, 0.23, 2.15]} scale={[-0.04, 0.04, 0.04]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|105_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.28, 1.15, 0.51]} rotation={[1.37, 0.84, -0.97]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|106_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.6, 0.68, 0.37]} rotation={[-1.42, -0.74, 2.44]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|107_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.5, -2.64, 0.47]} rotation={[0.67, 1.22, -2.24]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|108_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.05, -1.01, 0.52]} rotation={[-1.2, -0.08, -2.38]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|109_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.53, -5.28, 0.3]} rotation={[-1.5, -0.08, -2.42]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|110_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.77, 4.86, 0.42]} rotation={[0.79, 0.68, 1.67]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|111_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.85, -2.77, 0.42]} rotation={[1.63, -0.12, -1.36]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|112_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.53, 3.09, 0.42]} rotation={[-0.89, 0.38, -1.42]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|113_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.91, 1.34, 0.5]} rotation={[-0.48, 1.1, -3.06]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|114_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.54, 5.29, 0.44]} rotation={[-0.18, -0.54, -1.2]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|115_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.48, 4.7, 0.46]} rotation={[-0.04, -1.08, -0.76]} scale={[-0.15, 0.15, 0.15]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|116_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.78, 1.87, 0.32]} rotation={[-0.22, -0.61, 2.04]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|117_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.29, -6.27, 0.66]} rotation={[0.77, 1.24, 1.42]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|118_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.83, 5.33, 0.19]} rotation={[-0.46, -0.43, 0.02]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|119_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.31, -2.51, 0.41]} rotation={[1.68, -1.12, 2.7]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|120_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.52, -1.92, 0.31]} rotation={[-0.52, -0.42, -0.01]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|121_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.82, -0.23, 0.15]} rotation={[0.27, 0.58, -0.58]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|122_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.96, 0.98, 0.43]} rotation={[-1.8, -1.01, 2.86]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|123_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.42, -1.85, 0.15]} rotation={[0.26, 0.89, -2.76]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|124_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.56, -1.11, 0.16]} rotation={[0.23, 1.33, -0.26]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|125_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.66, 1.11, 0.47]} rotation={[0.67, 1.22, -2.24]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|126_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.7, -0.95, 0.5]} rotation={[-0.91, -0.94, 0.08]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|127_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.5, 1.04, 0.31]} rotation={[1.24, -0.83, 0.89]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|128_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.39, 3.18, 0.57]} rotation={[1.47, 0.2, -2.1]} scale={[-0.2, 0.2, 0.2]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|129_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.76, 5.52, 0.67]} rotation={[-0.89, -1.13, -2.35]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|130_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.81, -2.49, 0.59]} rotation={[0.49, -0.92, -1.17]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|131_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.71, 5.7, 0.48]} rotation={[1.32, 0.38, -0.31]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|132_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.31, 0.21, 0.37]} rotation={[-0.65, -1.12, -3.1]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|133_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.03, -2, 0.32]} rotation={[1.23, -0.47, 2.85]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|134_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.79, -1.67, 0.55]} rotation={[1.4, 0.54, 0.54]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|135_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.53, -4.51, 0.43]} rotation={[-0.39, 1.13, 2.16]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|136_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.58, -1.07, 0.32]} rotation={[-1.44, -0.62, -1.18]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|137_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.66, 0.18, 0.58]} rotation={[1.08, 0.68, 1.94]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|138_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.63, 1.3, 0.58]} rotation={[0.44, -0.99, -3.12]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|139_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.23, 6.24, 0.37]} rotation={[-0.07, -0.01, -1.64]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|140_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.05, -1.26, 0.55]} rotation={[-1.14, -0.77, -0.38]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|141_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.42, -3.3, 0.34]} rotation={[-1.18, -0.03, 1.92]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|142_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.95, 1.95, 0.22]} rotation={[-1.56, -1.2, 2.22]} scale={[-0.04, 0.04, 0.04]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|143_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.99, 1.45, 0.15]} rotation={[1.66, -0.9, -3.12]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|144_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.74, 0.86, 0.25]} rotation={[0.9, -0.93, -0.52]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|145_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.15, 2.95, 0.44]} rotation={[-0.23, 0.73, 2.26]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|146_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.06, 0.23, 0.32]} rotation={[0.13, 0.04, 2.42]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|147_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.14, 0.94, 0.65]} rotation={[-0.41, -0.94, -2.47]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|148_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.91, -2.93, 0.33]} rotation={[1.57, -0.75, -2.96]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|149_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.88, 0.37, 0.69]} rotation={[1.37, 0.57, -2.6]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|150_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.83, 3.9, 0.31]} rotation={[1.37, -0.03, -0.14]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|151_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.92, -1.4, 0.66]} rotation={[-1.44, 0.14, -1.69]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|152_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.47, -2.37, 0.4]} rotation={[-0.26, -0.86, 2.64]} scale={[-0.12, 0.12, 0.12]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|153_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.1, -3.19, 0.2]} rotation={[0.97, 0.47, 1.17]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|154_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.52, 2.83, 0.43]} rotation={[-1.26, -0.32, 1.77]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|155_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.67, 5.5, 0.32]} rotation={[-0.78, 0.21, -2.78]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|156_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.39, -1.38, 0.29]} rotation={[-0.92, 0.4, 1.24]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|157_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-6.1, 1.71, 0.33]} rotation={[1.05, -1.02, -1.03]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|158_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.28, 4.71, 0.65]} rotation={[1.6, -0.14, 0.69]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|159_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.58, 1.29, 0.22]} rotation={[1.46, 0.09, 2.74]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|160_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.05, -0.09, 0.47]} rotation={[1.07, 1.14, -1.49]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|161_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.47, 2.06, 0.67]} rotation={[-1.05, 0.88, 0.5]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|162_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.03, 4.71, 0.5]} rotation={[0.34, -0.06, 0.58]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|163_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.95, -0.52, 0.42]} rotation={[-1.45, 0.03, 2.89]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|164_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.33, -0.39, 0.16]} rotation={[-1.15, -0.25, 2]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|165_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.93, -2.42, 0.29]} rotation={[1.33, -1.17, 1.38]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|166_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.19, 2.63, 0.55]} rotation={[1.17, 0.23, -2.93]} scale={[-0.19, 0.19, 0.19]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|167_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.87, 2.68, 0.58]} rotation={[0.25, 0.34, -3.03]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|168_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.99, 1.23, 0.28]} rotation={[0.71, 1.05, 1.77]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|169_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.98, -0.02, 0.44]} rotation={[-0.68, 0.37, -1.39]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|170_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.42, 0.95, 0.17]} rotation={[-0.19, 0.4, 1.12]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|171_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.6, -0.49, 0.41]} rotation={[1.09, -0.81, -0.65]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|172_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.38, 0.73, 0.21]} rotation={[2.03, -1.15, 1.62]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|173_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.16, -3.55, 0.43]} rotation={[1.36, 0.57, 0.5]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|174_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.74, -1.62, 0.34]} rotation={[2.67, -1.38, 1.86]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|175_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.09, 4.84, 0.26]} rotation={[-0.89, 0.4, -1.44]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|176_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.85, -3.49, 0.67]} rotation={[0.61, 0.69, 2.75]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|177_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.29, 1.9, 0.31]} rotation={[-0.03, 0.98, -1.6]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|178_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.78, -1.52, 0.61]} rotation={[-1.35, -0.29, 1.57]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|179_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.78, 1.57, 0.66]} rotation={[-0.81, 0.21, 1.75]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|180_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.83, -4.09, 0.58]} rotation={[-1.94, -1.38, -1.07]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|181_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.33, -2.45, 0.44]} rotation={[0.78, -1.14, -0.86]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|182_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-6.03, -1.92, 0.52]} rotation={[-0.68, -0.62, 0.62]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|183_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.6, -2.77, 0.66]} rotation={[-1.01, 0.96, -0.51]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|184_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.22, 3.62, 0.33]} rotation={[1.05, 0.49, -2.06]} scale={[-0.09, 0.09, 0.09]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|185_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.21, 5.48, 0.38]} rotation={[0.25, -0.93, 1.7]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|186_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.17, -4.62, 0.25]} rotation={[0.2, -0.69, -2.1]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|187_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.74, 3.76, 0.35]} rotation={[1.01, -0.59, 2.29]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|188_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.6, -2.96, 0.25]} rotation={[0.9, -0.93, -0.52]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|189_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.98, 5.39, 0.66]} rotation={[1.27, 0.81, 2.66]} scale={[-0.25, 0.25, 0.25]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|190_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.98, 4.93, 0.52]} rotation={[-0.1, -0.8, 2.22]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|191_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.09, 3.08, 0.23]} rotation={[-1.6, -1.09, -1.51]} scale={[-0.04, 0.04, 0.04]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|192_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.18, -1.42, 0.26]} rotation={[0.05, -1.13, -0.82]} scale={[-0.05, 0.05, 0.05]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|193_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.81, 5.68, 0.56]} rotation={[0.3, -0.4, 0.53]} scale={[-0.2, 0.2, 0.2]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|194_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.66, -1.24, 0.42]} rotation={[-0.79, 0.51, 2.26]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|195_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.28, -2.57, 0.69]} rotation={[1.27, 0.1, -0.27]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|196_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.32, 0.14, 0.18]} rotation={[-0.09, -0.74, -2.46]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|197_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.3, 1.67, 0.49]} rotation={[-1.21, 0.66, 2.96]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|198_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.86, 1.32, 0.39]} rotation={[1.63, -0.87, -1.76]} scale={[-0.12, 0.12, 0.12]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|199_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.22, 3.21, 0.38]} rotation={[0.3, -0.4, 2.08]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|200_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.01, -2.8, 0.2]} rotation={[-1.78, -1.03, 1.95]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|201_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.1, -1.94, 0.59]} rotation={[1.34, 0.22, 1.39]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|202_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.51, 1.54, 0.39]} rotation={[0.95, 0.7, -3.02]} scale={[-0.12, 0.12, 0.12]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|203_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-0.49, -0.65, 0.64]} rotation={[1.12, -0.99, -0.39]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|204_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.8, -3.73, 0.29]} rotation={[1.2, 0.7, -0.73]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|205_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[6.24, 1.25, 0.34]} rotation={[-1.18, -0.89, -0.39]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|206_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.6, -3.31, 0.69]} rotation={[0.55, -0.28, 2.31]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|207_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.22, 0.92, 0.69]} rotation={[-0.98, -0.23, 0.92]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|208_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.26, -4.11, 0.43]} rotation={[-0.03, -0.01, -1.53]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|209_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.97, -0.59, 0.41]} rotation={[1.47, -0.93, -1.33]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|210_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.21, -0.6, 0.36]} rotation={[1.35, 0.25, -1.08]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|211_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.62, 6.3, 0.42]} rotation={[0.99, -1.06, 2.06]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|212_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.14, 0.72, 0.17]} rotation={[2.22, -1.29, -1.17]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|213_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.95, 2.17, 0.59]} rotation={[-0.74, -0.02, -1.04]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|214_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.68, -2.32, 0.52]} rotation={[-1.19, 0.87, -2.37]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|215_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.84, 3.03, 0.63]} rotation={[1.65, -0.93, 2.96]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|216_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.89, 0.77, 0.31]} rotation={[0.94, 0.57, -0.87]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|217_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[6.24, 1.24, 0.3]} rotation={[1.24, -0.41, -0.95]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|218_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.28, 2.87, 0.62]} rotation={[-1.78, -0.96, -0.1]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|219_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.7, -0.81, 0.3]} rotation={[1.15, 0.81, -0.39]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|220_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.76, 0.67, 0.18]} rotation={[-0.88, -1.09, 2.69]} scale={[-0.02, 0.02, 0.02]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|221_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.01, 3.87, 0.68]} rotation={[1.43, -0.64, 0.98]} scale={[-0.26, 0.26, 0.26]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|222_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.45, -1.39, 0.5]} rotation={[-1.11, 0.39, 1.09]} scale={[-0.17, 0.17, 0.17]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|223_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.73, -3.07, 0.61]} rotation={[1.23, -0.16, 1.35]} scale={[-0.22, 0.22, 0.22]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|224_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.36, -1.72, 0.43]} rotation={[-1.67, -0.89, -1.75]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|225_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.71, -2.45, 0.42]} rotation={[0.62, 0.66, -0.6]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|226_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[1.11, 1.72, 0.31]} rotation={[-1.55, -0.66, -0.82]} scale={[-0.08, 0.08, 0.08]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|227_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.15, -3.01, 0.15]} rotation={[1.37, -0.83, 2.39]} scale={0}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|228_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.61, 5.15, 0.58]} rotation={[1.38, -0.2, -2.12]} scale={[-0.21, 0.21, 0.21]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|229_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.54, 2.68, 0.45]} rotation={[-1.02, 0.25, -0.57]} scale={[-0.14, 0.14, 0.14]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|230_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.17, -0.33, 0.37]} rotation={[0.21, 0.39, 2.96]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|231_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.01, -0.9, 0.49]} rotation={[0.49, -0.37, -0.01]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|232_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-2.16, 5.95, 0.62]} rotation={[-0.44, 0.62, -0.61]} scale={[-0.23, 0.23, 0.23]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|233_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-1.35, -5.14, 0.3]} rotation={[-0.5, -0.04, 1.76]} scale={[-0.07, 0.07, 0.07]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|234_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.18, -1.31, 0.51]} rotation={[-1.49, 0.06, 1.74]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|235_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.45, -0.78, 0.41]} rotation={[-1.55, -0.58, 0.7]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|236_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.22, -0.93, 0.17]} rotation={[1.13, 0.96, -1.07]} scale={[-0.01, 0.01, 0.01]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|237_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.78, 1.72, 0.36]} rotation={[-1.84, -1.22, -2.1]} scale={[-0.1, 0.1, 0.1]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|238_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[5.61, -2.94, 0.51]} rotation={[-1.25, 0.53, -1.77]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|239_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[2.3, 4.5, 0.42]} rotation={[-0.44, 0.53, 3.06]} scale={[-0.13, 0.13, 0.13]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|240_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-5.84, -1.12, 0.65]} rotation={[2.53, -1.37, -2.22]} scale={[-0.24, 0.24, 0.24]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|241_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0.46, 2.01, 0.2]} rotation={[-0.47, -0.43, 2.2]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|242_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[3.4, 0.55, 0.37]} rotation={[-1.13, -1.29, 2.77]} scale={[-0.11, 0.11, 0.11]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|243_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[4.13, 1.18, 0.53]} rotation={[0.52, 0.24, -0.26]} scale={[-0.18, 0.18, 0.18]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|244_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-4.2, 1.27, 0.2]} rotation={[0.23, 0.41, -1]} scale={[-0.03, 0.03, 0.03]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|245_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[-3.14, -4.16, 0.48]} rotation={[0.59, -0.98, -0.29]} scale={[-0.16, 0.16, 0.16]}>
              <mesh geometry={nodes['rock_Duplicator|rock_-_copy|Dupli|246_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <group position={[0, 0, 0.14]} rotation={[-3.1, 0.2, 0.2]} scale={[-0.48, 0.48, 0.48]}>
              <mesh geometry={nodes['rock_-_copy_ROCK_0'].geometry} material={materials.ROCK} />
            </group>
            <mesh geometry={nodes.rock_Duplicator__0.geometry} material={materials.branch_Duplicator__0} />
          </group>
          {/* <group position={[0, 0, -5.1]} rotation={[Math.PI / 2, 0, 0]} scale={[-636.29, 636.29, 636.29]}>
            <mesh geometry={nodes.GROUND001_GROUND001_0.geometry} material={materials['GROUND.001']} />
          </group> */}
          <group position={[67.13, 23.65, 482.88]} rotation={[-2.33, -0.38, -2.96]} scale={63.88}>
            <mesh geometry={nodes.grass099_GRASS_0.geometry} material={materials.GRASS} />
            <mesh geometry={nodes.grass099_GRASS_0_1.geometry} material={materials.GRASS} />
            <mesh geometry={nodes.grass099_GRASS_0_2.geometry} material={materials.GRASS} />
            <mesh geometry={nodes.grass099_GRASS_0_3.geometry} material={materials.GRASS} />
            <mesh geometry={nodes.grass099_GRASS_0_4.geometry} material={materials.GRASS} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stylizedGround.glb')
