/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sahir Virmani (https://sketchfab.com/sahirvirmani)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/giant-low-poly-tree-acfd2b7f80894848b56c2ac8e7e59572
title: Giant Low Poly Tree
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Cylinder_0: THREE.Mesh;
		Icosphere_0: THREE.Mesh;
		Icosphere001_0: THREE.Mesh;
		Icosphere002_0: THREE.Mesh;
		Icosphere003_0: THREE.Mesh;
		Icosphere004_0: THREE.Mesh;
		Icosphere005_0: THREE.Mesh;
	};
	materials: {
		tree_wood: THREE.MeshStandardMaterial;
		["leaf_green.003"]: THREE.MeshStandardMaterial;
		["leaf_green.004"]: THREE.MeshStandardMaterial;
		["leaf_green.001"]: THREE.MeshStandardMaterial;
		leaf_green: THREE.MeshStandardMaterial;
		["leaf_green.002"]: THREE.MeshStandardMaterial;
		["leaf_green.005"]: THREE.MeshStandardMaterial;
	};
};

export function Tree(props: JSX.IntrinsicElements["group"]) {
	//@ts-ignore
	const { nodes, materials } = useGLTF("/tree.glb") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
				<group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
				<group scale={[1, 1, 6.69]}>
					<mesh
						geometry={nodes.Cylinder_0.geometry}
						material={materials.tree_wood}
					/>
				</group>
				<group position={[0.03, 1.99, 20.57]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere_0.geometry}
						material={materials["leaf_green.003"]}
					/>
				</group>
				<group position={[-12.06, 11.58, 18.51]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere001_0.geometry}
						material={materials["leaf_green.004"]}
					/>
				</group>
				<group position={[-12.83, -4.37, 18.68]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere002_0.geometry}
						material={materials["leaf_green.001"]}
					/>
				</group>
				<group position={[13.32, 3.81, 20.57]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere003_0.geometry}
						material={materials.leaf_green}
					/>
				</group>
				<group position={[5.02, -8, 16.59]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere004_0.geometry}
						material={materials["leaf_green.002"]}
					/>
				</group>
				<group position={[1.94, 12.6, 17.61]} scale={2.44}>
					<mesh
						geometry={nodes.Icosphere005_0.geometry}
						material={materials["leaf_green.005"]}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/tree.glb");
